spring:
  application:
    name: spirng-boot-rabbitmq-demo
  groovy:
    template:
      check-template-location: false
  datasource:
    url: jdbc:mysql://192.168.183.125:3306/jlxf_cs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: sxkj0818web
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
logging:
  config: classpath:logback.groovy
